### ISSUE TITLE
Add skins for missing Yosys RTL cells

### ISSUE THREAD

**Issue by nobodywasishere** [nturley/netlistsvg#104]
Some cells from Yosys that could use a skin. I created this issue to figure out which cells should get skinned, as well as what skin they should get. I'm pulling information from the latest version of the [Yosys manual](https://github.com/YosysHQ/yosys/blob/master/manual/CHAPTER_CellLib.tex). All ideas, comments, and constructive criticism welcome.

### unary operators

- [x] `$pos`, making into a plus sign may get confusing with addition
- [x] `$neg`, making into a minus may get confusing with subtraction
- [x] `$reduce_and` should be added as an alias to `and`
- [x] `$reduce_or` and `reduce_bool` should be added as aliases to `or`

### binary operators

- [x] `$shl`, `$shr`, `$sshl`, `$sshr` could be done with just `<<`,  `>>`, `<<<`, and `>>>` respectively
- [x] `$mul`,  `*` or `x` could work
- [x] `$div`, `/` could work
- [x] `$mod`, `%` could work
- [x] `$pow`, `^` or `a^b` may work
- [x] `$eqx` may be added as an alias to `$eq`
- [x] `$ne` and `$nex` could have a `=/=` symbol

### registers

- [ ] `$sr`, I don't think this one needs a skin
- [x] `$adff`, same as `$dff` but have an `ARST` (asynchronous reset) port. This could simply just be on the bottom of the current `$dff` skin
- [x] `$sdff`, same as `$dff` but have an `SRST` (synchronous reset) port. This could simply just be on the bottom of the current `$dff` skin, though not sure how to distinguish from `$adff`, maybe by putting an `A` or `S` next to the reset port
- [x] `$dlatch`, `$dlatchsr`, and `$adlatch`, not sure what this one would look like
- [ ] `$dffsr`, not sure what this one would look like

There are several other register variants listed in the manual that may be too niche / difficult to properly define a skin for. These are `$dffe`, `$adffe`, `$dffsre`, `$sdffe`, and `$sdffce`.

### memories

- [ ] `$mem`, `$memrd`, `$memwr`, `$meminit` - I'm not sure what to do for these, if anything should be done

 ### gates

- [x] `$_BUF_`
- [x]  `$_ANDNOT_`, `$_ORNOT_`
- [x] `$_AOI3_`, `$_OAI3_`, `$_AOI4_`, `$_OAI4_`
- [ ] `$_MUX4_`, `$_MUX8_`, `$_MUX16_`

**Comment by mithro** [comment]
@nobodywasishere - I'm sure I had some of these already created somewhere but I can't seem to find them now....

**Comment by mithro** [comment]
Apparently I had some stuff at https://github.com/mithro/symbiflow-arch-defs/commit/bd58242a08c838492a7b30533aeece218a64c37a?short_path=e0d91d8#diff-e0d91d811dd290812325d4ed53ad63fc429631785ea6edaf4c835205aef59563

**Comment by mithro** [comment]
![image](https://user-images.githubusercontent.com/21212/113381663-63fc6580-9334-11eb-900d-b059c9ced366.png)

**Comment by mithro** [comment]
There seems to be some documentation at https://github.com/mithro/symbiflow-arch-defs/blob/4ac22bdc2f6261c09db5f00034b52c66d5f482ce/vpr/latches/README.md

**Comment by mithro** [comment]
https://raw.githubusercontent.com/mithro/symbiflow-arch-defs/f47a4e1539c844aac164692f4fdb164f19740861/common/svg/default.svg

![Screenshot from 2021-04-01 21-54-23](https://user-images.githubusercontent.com/21212/113381841-da996300-9334-11eb-98cf-fe78752f3b1b.png)

**Comment by mithro** [comment]
https://raw.githubusercontent.com/mithro/symbiflow-arch-defs/277b176d04243067af4bd37f12be03347275593f/common/netlistsvg.svg

**Comment by mithro** [comment]
And on the topic of flip flops and latches - I have a giant table of flip flops and latches found in various FPGA architectures at https://docs.google.com/spreadsheets/d/16yvScRkedOkPCRBSInFuHE_cUMD8Ls-b9KFmHocpC-o/edit#gid=0 and some details about the mapping between them at https://docs.google.com/spreadsheets/d/1pWjU8RujiGdlr-8iG66O1rvognNHgtnNVvCjSfksH-4/edit#gid=0

**Comment by mithro** [comment]
There is also some code to generate flip flops from the spreadsheet at https://github.com/mithro/symbiflow-arch-defs/blob/v2x-latches2/utils/flipflop-generate.py

**Comment by nobodywasishere** [comment]
![image](https://user-images.githubusercontent.com/32797552/131270141-65560f1e-2fbc-491b-bfb1-b9975cef74d2.png)
Work in progress... Thoughts? Still need to work on the flip flops / latches. Thank you for all the information mithro!

**Comment by nobodywasishere** [comment]
So I've worked a little bit more on this, specifically on the latches / flip-flops. For latches/ffs with a reset, I've just added a port onto the bottom that can be populated if it exists, and I've not distinguished between synchronous and asynchronous (yet). I also added `-bus` variants for these.

![image](https://user-images.githubusercontent.com/32797552/134747101-c0d04c1c-75f1-432d-8311-c9f7ad7099b5.png)

Here's an example of one diagram before:

![image](https://user-images.githubusercontent.com/32797552/134747246-ae2f9cde-4c53-4b34-ad66-0e6fe3cf7df7.png)

And after:

![image](https://user-images.githubusercontent.com/32797552/134747264-88c9c426-d747-4e84-b34f-1189d0999773.png)

**Comment by mithro** [comment]
This looks awesome!

**Comment by rishubn** [comment]
Are there plans to unroll or devise skins for complex gates within the cell library such as _AOI3_

https://github.com/YosysHQ/yosys/blob/fdb19a5b3a10572b1b84a26306ec5e83a4eff613/manual/CHAPTER_CellLib.tex#L637

**Comment by nobodywasishere** [comment]
I had not planned on doing those, though I can look into it. Do you have an idea / sketch of what you think it could look like?

**Comment by rishubn** [comment]
@nobodywasishere 

It would make sense to unroll these, currently their are represented as black boxes, but maybe this needs to be done on the algorithm side, not the skins

![image](https://user-images.githubusercontent.com/6591138/142179288-fc1e8426-7255-4ae0-9666-5f0bf330cd64.png)

**Comment by mithro** [comment]
Some suggestions from a quick google search;
 - http://www.vlsi-expert.com/2018/01/aoi-and-or-inverter-cell.html
 - https://en.wikipedia.org/wiki/AND-OR-Invert

![image](https://user-images.githubusercontent.com/21212/142476036-cacb0aa2-6f0b-48b2-881c-6febb6c3089a.png)

![image](https://user-images.githubusercontent.com/21212/142475935-094098b1-8654-444d-84f1-604decb919cb.png)
> 2-2 AOI Symbol

**Comment by mithro** [comment]
![image](https://user-images.githubusercontent.com/21212/142476136-a7eba182-e82a-46cb-b19b-c4c7e1962af2.png)

**Comment by nobodywasishere** [comment]
Progress update:
- Added `$_{AND,OR}NOT_`
- Added `$_{AOI,OAI}{3,4}_`
- Added the fix in #115
- Attempted a memory cell, but not sure how good a representation this is (it's still a WIP)

![image](https://user-images.githubusercontent.com/32797552/147784516-f1b968e3-7b6d-49a2-8536-26c2559aa5a1.png)

**Comment by mithro** [comment]
All looks pretty awesome to me!
