### ISSUE TITLE
Demo webpage looks bad in Safari

### ISSUE THREAD

**Issue by nturley** [nturley/netlistsvg#21]
I think mostly it's the fonts. It uses a serif font for test, a sans-serif font for buttons, and the textarea font isn't fixed width.

**Comment by kasbah** [comment]
Those are just all the defaults. I normally use [Semantic-UI](https://semantic-ui.com/introduction/getting-started.html) when I want to make something look decent without much work (e.g. the [electro-grammar demo](https://monostable.github.io/electro-grammar/)).

**Comment by nturley** [comment]
Yeah, I was just going to add a couple lines of CSS to get the fonts to look okay, but yeah Semantic-UI looks cool.
