### ISSUE TITLE
Indicate bus width

### ISSUE THREAD

**Issue by kasbah** [nturley/netlistsvg#26]
Would be nice to be able to easily see the width of buses other than from the splits and constants.

**Comment by nturley** [comment]
ELK supports edge labels, but it's going to really clutter up the schematic if we have every single edge labeled. So I think the only tricky part about this is deciding which edges to add labels to.

Yosys also provides net names, so in theory we could also consider putting the netnames as an edge label.

**Comment by kasbah** [comment]
I could have sworn there was some universal convention in digital logic schematics to indicate bus widths with some slanted  edges. Something like this:

![](https://cloud.monostable.co.uk/bus.svg)

But maybe dotted or squiggly somehow? I can't find any examples. Do you know what I am thinking of? This would have to be done with a graph node.

**Comment by kasbah** [comment]
I guess the convention is just a single slanted line and a number next to it. 

![image](https://user-images.githubusercontent.com/206854/34577661-35e20738-f182-11e7-8ca1-5942a4d8fed7.png)

from: https://tex.stackexchange.com/questions/125460/drawing-bus-width-like-markers-with-number-on-arrows

**Comment by nturley** [comment]
finding the coordinates of the slanty line also makes this a little tricky.

**Comment by rjordans** [comment]
Another option may be to add the slanted line with number as one of the nodes on the line for ELK to place for you?  That should help in keeping things clean

**Comment by nturley** [comment]
I like that solution. It would add more columns but I think that is fine.

**Comment by stevenbell** [comment]
This would be really helpful to me.  Even just using a bold line to indicate a bus versus a single wire would be a big help.

I'm happy to submit a PR if you can point me in the right direction to get started.

**Comment by nobodywasishere** [comment]
I got double line thickness to indicate a bus working with [this commit](https://github.com/nobodywasishere/netlistsvg/commit/7dc47a6aa10b30be236f8fe689b5134419925853). 

Before:

![image](https://user-images.githubusercontent.com/32797552/111736657-a9a93080-8854-11eb-9235-dea54d8a2e9e.png)

After (along with some other changes I made):

![image1](https://user-images.githubusercontent.com/32797552/111736672-ae6de480-8854-11eb-8f48-bd387a6df374.png)


I've also started [looking into](https://github.com/nobodywasishere/netlistsvg/commit/c2300a7d2f6ba6d0bf8f2ef41e1acdf82013c5a0) indicating the bus width with an [edge label](https://www.eclipse.org/elk/reference/options/org-eclipse-elk-edgeLabels-inline.html) but so far it's proved unsuccessful. ElkJS seems to make space for the labels but doesn't actually place them for some reason.

**Comment by nturley-copia** [comment]
That looks great! Well done

**Comment by nturley** [comment]
Looks great. Well done.

**Comment by rjordans** [comment]
that's looking nice already!

**Comment by nobodywasishere** [comment]
I'm also on the [netlistsvg Gitter](https://gitter.im/netlistsvg/Lobby) if anyone wants to talk about this there.

**Comment by mithro** [comment]
This is super cool!

**Comment by mithro** [comment]
I would love to see this integrated into netlistsvg and demos in https://github.com/SymbiFlow/sphinxcontrib-hdl-diagrams
