### ISSUE TITLE
Add text/values to parts (especially skinned)

### ISSUE THREAD

**Issue by amstan** [nturley/netlistsvg#53]
I would like to label my resistors, capacitors with reference designators (R1, C1) and values (1k, 100nF).

Right now there's no way to add any text except by changing the type to something custom (to disable the skin), even then, would be nice to support multiple lines.

For the VCC part in the analog skin, I would like to change the text "VCC" dynamically, for designs that have more than one voltage rail. Perhaps that could be the VCC part's "value".

Another smaller request that might be related: for blocky chip type parts, a way to put the pin names inside and pin numbers outside. For now my workaround is to just have the pin numbers in () and live with the fact that everything's outside of the block.

**Comment by amstan** [comment]
I'm really sorry, this looks to be handled by https://github.com/nturley/netlistsvg/pull/38

**Comment by amstan** [comment]
Nevermind.

I saw this picture and got excited, but we don't do that yet:
![labels!](https://user-images.githubusercontent.com/741807/35674216-3123d082-0744-11e8-8ea7-a1e86a7bc107.png)

We would need to edit the default skin file to have those attributes for the resistors and other parts.

**Comment by nturley** [comment]
Yeah, ideally each cell template should be able to add as many text boxes as it likes and indicate which attributes from the netlist cell to pull them from. I think that's where we were going with #35?

**Comment by nturley** [comment]
ah, I see what happened here. It was completed but never added to the analog skin. I'll add them back.

**Comment by nturley** [comment]
In addition to just adding the labels to the skin, there's some additional work to getting the labels into ELK so that layout routes around them.

**Comment by amstan** [comment]
Looks good so far! Thanks!
