### ISSUE TITLE
Add analog example to README

### ISSUE THREAD

**Issue by nturley** [nturley/netlistsvg#54]
IMO the analog skin still doesn't work nearly as well as the digital one, but it is still picking up users. We should add at least one analog example to help analog users get started.

**Comment by amstan** [comment]
We should probably have the [nice class A amplifier](https://github.com/nturley/netlistsvg/blob/master/test/analog/common_emitter_full.json), though, would be nice if it didn't have that redundant base connection.

Also how about a regulator circuit?
![regulator](https://user-images.githubusercontent.com/160217/56076972-59351880-5d8b-11e9-8a50-759f994e405d.png)
<details><summary>regulator.json</summary>

	{
		modules: {
			undefined: {
				cells: {
					C1: {
						type: "c_v",
						connections: {
							A: [
								1
							],
							B: [
								2
							]
						}
					},
					VIN: {
						type: "vcc",
						attributes: {
							value: "VIN"
						},
						connections: {
							A: [
								1
							]
						}
					},
					GNDC1: {
						type: "gnd",
						connections: {
							A: [
								2
							]
						}
					},
					U1: {
						type: "U1 (LM317)",
						port_directions: {
							IN: "input",
							ADJ: "output",
							OUT: "output"
						},
						connections: {
							IN: [
								1
							],
							OUT: [
								3
							],
							ADJ: [
								5
							]
						}
					},
					VOUT: {
						type: "vcc",
						attributes: {
							value: "VOUT"
						},
						connections: {
							A: [
								3
							]
						}
					},
					C2: {
						type: "c_v",
						connections: {
							A: [
								3
							],
							B: [
								4
							]
						}
					},
					GNDC2: {
						type: "gnd",
						connections: {
							A: [
								4
							]
						}
					},
					R1: {
						type: "r_v",
						connections: {
							A: [
								3
							],
							B: [
								5
							]
						}
					},
					R2: {
						type: "r_v",
						connections: {
							A: [
								5
							],
							B: [
								6
							]
						}
					},
					GNDR2: {
						type: "gnd",
						connections: {
							A: [
								6
							]
						}
					}
				}
			}
		}
	}
</details>
