### ISSUE TITLE
How did you get the "default.svg" file?

### ISSUE THREAD

**Issue by dcsgman** [nturley/netlistsvg#70]

**Comment by kasbah** [comment]
[It's here](https://github.com/nturley/netlistsvg/blob/f1e4c9639b3c88d40e8032d4fa1d93116d19bfc2/lib/default.svg), or are you asking something else?

**Comment by dcsgman** [comment]
Yeah, Thank you! But I wanna know how to generate this file? Can u tell me?

Best regards

Rongliang Fu
TEL:+86 18881814693

________________________________

**Comment by nturley** [comment]
Its mostly written by hand. You can edit the graphical parts using an SVG editor like inkscape but it requires annotations about where the ports are and the names of the aliases and so that part needs to be done by hand.

**Comment by dcsgman** [comment]
OK. Thank you very much!

Best regards

Rongliang Fu
TEL:+86 18881814693

________________________________
