### ISSUE TITLE
How to run tests in test

### ISSUE THREAD

**Issue by mithro** [nturley/netlistsvg#79]
It would be good if the README had information on how to run the tests found in the [test directory](https://github.com/nturley/netlistsvg/tree/master/test).

**Comment by rjordans** [comment]
This took me some time to get figured out as well.  My steps so far (which seems to work):

- clone repository
- ``npm install`` to get dependencies
- ``npm run test`` to run tests and lint checker

Some more ``npm run`` scripts can be found listed in the [package.json](https://github.com/nturley/netlistsvg/blob/master/package.json#L30) file section _scripts_
