### ISSUE TITLE
doglegs in schematic

### ISSUE THREAD

**Issue by xesscorp** [nturley/netlistsvg#95]
I'm developing a skin file, but when I generate a schematic it is placing "doglegs" in the wiring. Is there something special I have to do to the symbols in my skin file? I've noticed that I need to specify the width and height of the bounding box, but there's no place for the origin. How does netlistsvg/elkjs figure out where the bounding box is in relation to the I/O pins?

![test4](https://user-images.githubusercontent.com/845595/88306332-99967c80-ccd8-11ea-8ba2-7a0f901af427.png)

**Comment by kasbah** [comment]
I can't remember if `postCompaction` is used in netlistsvg now. It might help to try it if it isn't. Previously mentioned: https://github.com/nturley/netlistsvg/pull/40#issuecomment-394457005
