### ISSUE TITLE
Names with dots not rendered.

### ISSUE THREAD

**Issue by Zottel** [nturley/netlistsvg#97]
When I render circuits with input/output names containing dots, i.e. from SystemVerilog interfaces, these names are not rendered. Is this a bug or intended behaviour? Is there a way to escape these names or should I remove them from my output?
Looking forward to your reply and thank you for the awesome tool :)

[something.withdots.json.txt](https://github.com/nturley/netlistsvg/files/5364213/something.withdots.json.txt)

![something withdots](https://user-images.githubusercontent.com/84425/95729993-f40efb80-0c7d-11eb-9979-4d72dbca5ab8.png)

[something.withoutdots.json.txt](https://github.com/nturley/netlistsvg/files/5364214/something.withoutdots.json.txt)

![something withoutdots](https://user-images.githubusercontent.com/84425/95730007-f96c4600-0c7d-11eb-9aaa-ac3cb4b27acf.png)

**Comment by nturley** [comment]
netlistsvg uses periods internally for some internal naming so I'm guessing that must've confused it. I didn't intend not to support names with dots though so I suppose it's a bug.

**Comment by Zottel** [comment]
Fixed by 2c1fb82.
